name = "GeneralTools"
uuid = "e6213164-e472-4082-9e51-db24b57ca6ab"
authors = ["okatsn <49422823+okatsn@users.noreply.github.com>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
